Repository SENG480a-NutriDine/webapp, pull requests merged in 2024-04, with the labels that each got.

#36 detailed food modal fix
  nutridine/src/components/DetailedFoodModalContent.js
Labels: bug

#37 Login/Reg Styling Changes
  nutridine/src/screens/authentication/RegisterForm.js
  nutridine/src/screens/authentication/Signin.js
  nutridine/src/screens/authentication/Signup.js
Labels: enhancement

#29 16 restaurant page UI
  nutridine/src/App.js
  nutridine/src/assets/RestaurantsLogos/7-11.png
  nutridine/src/assets/RestaurantsLogos/A&W (Canada).png
  nutridine/src/assets/RestaurantsLogos/Bento Sushi.png
  nutridine/src/assets/RestaurantsLogos/Boston Pizza.png
  nutridine/src/assets/RestaurantsLogos/Browns Socialhouse.png
  nutridine/src/assets/RestaurantsLogos/Burger King.png
  nutridine/src/assets/RestaurantsLogos/Cinnabon.png
  nutridine/src/assets/RestaurantsLogos/Cinnzeo.png
  nutridine/src/assets/RestaurantsLogos/Cora.png
  nutridine/src/assets/RestaurantsLogos/Costco Food Court.png
  nutridine/src/assets/RestaurantsLogos/Dairy Queen.png
  nutridine/src/assets/RestaurantsLogos/De Dutch Pannekoek House.png
  nutridine/src/assets/RestaurantsLogos/Domino's.png
  nutridine/src/assets/RestaurantsLogos/Earls.png
  nutridine/src/assets/RestaurantsLogos/Edo Japan.png
  nutridine/src/assets/RestaurantsLogos/Fatburger.png
  nutridine/src/assets/RestaurantsLogos/Freshii.png
  nutridine/src/assets/RestaurantsLogos/KFC.png
  nutridine/src/assets/RestaurantsLogos/Lee's Famous Recipe Chicken.png
  nutridine/src/assets/RestaurantsLogos/Little Caesars Pizza.png
  nutridine/src/assets/RestaurantsLogos/Manchu Wok.png
  nutridine/src/assets/RestaurantsLogos/McDonald's Canada.png
  nutridine/src/assets/RestaurantsLogos/Mucho Burrito.png
  nutridine/src/assets/RestaurantsLogos/New York Fries.png
  nutridine/src/assets/RestaurantsLogos/Orange Julius.png
  nutridine/src/assets/RestaurantsLogos/Panago Pizza.png
  nutridine/src/assets/RestaurantsLogos/Papa John’s.png
  nutridine/src/assets/RestaurantsLogos/Pizza Hut.png
  nutridine/src/assets/RestaurantsLogos/Popeyes.png
  nutridine/src/assets/RestaurantsLogos/Red Robin.png
  nutridine/src/assets/RestaurantsLogos/Starbucks.png
  nutridine/src/assets/RestaurantsLogos/Subway.png
  nutridine/src/assets/RestaurantsLogos/Swiss Chalet.png
  nutridine/src/assets/RestaurantsLogos/Thai Express.png
  nutridine/src/assets/RestaurantsLogos/The Keg.png
  nutridine/src/assets/RestaurantsLogos/The Old Spaghetti Factory.png
  nutridine/src/assets/RestaurantsLogos/Tim Horton's.png
  nutridine/src/assets/RestaurantsLogos/White Spot Restaurants.png
  nutridine/src/hooks/Meals/useMealsByRestaurant.js
  nutridine/src/screens/authentication/RegisterForm.js
  nutridine/src/screens/restaurants/MealsPage.js
  nutridine/src/screens/restaurants/RestaurantsPage.js
Labels: task

#44 Icons
  nutridine/src/components/FilterGroup.js
  nutridine/src/screens/Homepage.js
Labels: enhancement
