Repository SENG480a-NutriDine/webapp, pull requests merged in 2024-03, with the labels that each got.

#1 Loading Page
  nutridine/src/App.js
  nutridine/src/index.js
  nutridine/src/screens/loading/IPiece.js
  nutridine/src/screens/loading/JPiece.js
  nutridine/src/screens/loading/LPiece.js
  nutridine/src/screens/loading/OPiece.js
  nutridine/src/screens/loading/SPiece.js
  nutridine/src/screens/loading/TPiece.js
  nutridine/src/screens/loading/TetrisLoader.js
  nutridine/src/screens/loading/ZPiece.js
  nutridine/src/screens/loading/index.js
  nutridine/src/screens/loading/styles.css
  nutridine/src/theme.js
Labels: task

#3 Setup NutritionIx Database & make hook to filter by macros
  nutridine/package-lock.json
  nutridine/package.json
  nutridine/src/App.js
  nutridine/src/components/FoodCard.js
  nutridine/src/constants/brandIds.js
  nutridine/src/constants/nutritionIxIds.js
  nutridine/src/hooks/useMealsByMacros.js
  nutridine/src/images/nutritionIx_credit.png
Labels: task

#7 Detailed Food Modal
  nutridine/package-lock.json
  nutridine/src/App.js
  nutridine/src/Layout.js
  nutridine/src/components/DetailedFoodModalContent.js
  nutridine/src/components/FoodCard.js
  nutridine/src/components/LoadingSpinner.js
  nutridine/src/components/NutritionFacts.js
  nutridine/src/components/navbar/MenuItem.js
  nutridine/src/components/navbar/MenuLinks.js
  nutridine/src/components/navbar/Navbar.js
  nutridine/src/contexts/MealsContext.js
  nutridine/src/hooks/useMealById.js
  nutridine/src/hooks/useMealsByMacros.js
  nutridine/src/index.js
  nutridine/src/screens/macro/MacroPage.js
Labels: task

#6 Macro Page
  nutridine/package-lock.json
  nutridine/src/hooks/useMealsByMacros.js
  nutridine/src/screens/macro/MacroPage.js
Labels: task

#11 navbar color fix
  nutridine/src/components/navbar/MenuLinks.js
Labels: bug

#14 stepper fix
  nutridine/src/screens/macro/MacroPage.js
Labels: bug

#12 Navbar Router Integration
  nutridine/package-lock.json
  nutridine/package.json
  nutridine/src/App.js
  nutridine/src/Layout.js
  nutridine/src/assets/images/nutritionIx_credit.png
  nutridine/src/assets/images/splash.svg
  nutridine/src/components/navbar/MenuItem.js
  nutridine/src/components/navbar/MenuLinks.js
  nutridine/src/index.js
Labels: task

#20 Hover Navbar Item
  nutridine/src/components/navbar/MenuItem.js
  nutridine/src/components/navbar/MenuLinks.js
Labels: enhancement

#15 Integrate Detailed Food Modal, CSS & Linter Cleanup
  nutridine/src/App.js
  nutridine/src/Layout.js
  nutridine/src/components/DetailedFoodModalContent.js
  nutridine/src/components/FoodCard.js
  nutridine/src/components/FoodDisplay/FoodCard.js
  nutridine/src/components/FoodDisplay/FoodCardList.js
  nutridine/src/components/NutritionFacts.js
  nutridine/src/components/navbar/MenuItem.js
  nutridine/src/components/navbar/MenuLinks.js
  nutridine/src/components/navbar/Navbar.js
  nutridine/src/hooks/useMealsByMacros.js
  nutridine/src/screens/macro/MacroPage.js
Labels: enhancement, task

#26 Firebase Auth and login/signup page
  nutridine/package-lock.json
  nutridine/package.json
  nutridine/src/App.js
  nutridine/src/components/navbar/MenuLinks.js
  nutridine/src/components/navbar/Navbar.js
  nutridine/src/firebaseConfig.js
  nutridine/src/screens/authentication/OuathButtonGroup.js
  nutridine/src/screens/authentication/PasswordField.js
  nutridine/src/screens/authentication/Signin.js
  nutridine/src/screens/authentication/Signup.js
  nutridine/src/screens/macro/MacroPage.js
Labels: task

#27 Firebasew Auth Continued
  nutridine/src/App.js
  nutridine/src/Layout.js
  nutridine/src/components/DetailedFoodModalContent.js
  nutridine/src/components/navbar/MenuLinks.js
  nutridine/src/contexts/AuthContext.js
  nutridine/src/hooks/AuthService/authService.js
  nutridine/src/hooks/Meals/useMealById.js
  nutridine/src/hooks/Meals/useMealsByMacros.js
  nutridine/src/index.js
  nutridine/src/screens/authentication/OuathButtonGroup.js
  nutridine/src/screens/authentication/PasswordField.js
  nutridine/src/screens/authentication/PasswordReset.js
  nutridine/src/screens/authentication/ProfilePage.js
  nutridine/src/screens/authentication/RegisterForm.js
  nutridine/src/screens/authentication/Signin.js
  nutridine/src/screens/authentication/Signup.js
  nutridine/src/screens/macro/MacroPage.js
Labels: enhancement, task

#28 Nutrient Preferences Form
  nutridine/src/App.js
  nutridine/src/components/DetailedFoodModalContent.js
  nutridine/src/components/NutritionFacts.js
  nutridine/src/constants/dailyMaximums.js
  nutridine/src/constants/mockData/detailedMeal.js
  nutridine/src/constants/nutrientWatchList.js
  nutridine/src/hooks/useNutrientPreferences.js
  nutridine/src/hooks/useSubmitNutrientPreferences.js
  nutridine/src/screens/authentication/ProfilePage.js
  nutridine/src/screens/authentication/RegisterForm.js
  nutridine/src/screens/nutrientPreferences/NutrientPreferences.js
  nutridine/src/screens/nutrientPreferences/Tag.js
  nutridine/src/theme.js
Labels: task

#31 Navbar MenuItem fix
  nutridine/src/components/navbar/CustomMenu.js
  nutridine/src/components/navbar/MenuItem.js
  nutridine/src/components/navbar/MenuLinks.js
Labels: enhancement

#32 Simple Profile page
  nutridine/src/screens/authentication/ProfilePage.js
  nutridine/src/screens/authentication/RegisterForm.js
  nutridine/src/screens/nutrientPreferences/NutrientPreferences.js
  nutridine/src/theme.js
Labels: enhancement

#30 Homepage PR
  nutridine/package-lock.json
  nutridine/package.json
  nutridine/src/App.js
  nutridine/src/components/FilterGroup.js
  nutridine/src/components/navbar/MenuLinks.js
  nutridine/src/hooks/Meals/useMealsByQuery.js
  nutridine/src/screens/Homepage.js
Labels: enhancement
